### ISSUE TITLE
Replace the git library

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-pushy#11]
`sebastian/git` is deprecated and there are better alternatives that will allow us to simplify our code and the enrich the UI (eg. #10).

Mentioned in #4 too.

**Comment by pamtbaau** [comment]
The one mentioned in #4 (https://github.com/symplify/git-wrapper) requires PHP >= 8. Does that pose a limitation?

**Comment by hughbris** [comment]
Oh yeah it does for me ATM, unfortunately.

**Comment by hughbris** [comment]
I did another quick search. Only found ones I'd starred before. Lots of noise in these searches of course. Here are some findings.

**[Git.php](https://github.com/kbjr/Git.php)**: The docs are so basic and the open issues are so old that I am scared off.

**[git-php](https://github.com/czproject/git-php)**: feature-rich, simple, documented, maintained. worth following up.

Some more are listed in a [similar GitSync issue](https://github.com/trilbymedia/grav-plugin-git-sync/issues/145) but none suitable and it's reasonably obvious why in each case.

I like the idea of not requiring PHP exec permission in a library because it opens the plugin up to being used in more secure setups. The less environment requirements the better.

**Comment by hughbris** [comment]
Effectively completed in 941afbc and merged into `develop` in f52dbc0.

**Comment by hughbris** [comment]
Because of inadequate `status` output (basically just git's crap options) in czproject/git-php, I don't think I'll be able to solve both #8 and #32. May need to reopen this and explore more options. Have found [GitElephant](https://github.com/matteosister/GitElephant), which promises tokenised/structured output, let's see.
