### ISSUE TITLE
Internationalise strings in the UI

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-pushy#29]
PHP/Twig parts are a straightforward task, not sure if there's an elegant way to achieve this in JS/TS.

**Comment by pamtbaau** [comment]
UI strings that are being set using ts/js, can also be stored inside *translations.yaml*. Translations of relevant UI strings can be collected inside PHP and transformed into a map of key/value pairs, which can be injected into ts/js using the Asset Manager. In ts/js, the map can be read and used to create dynamic output.

**Comment by hughbris** [comment]
Thanks, I've done this plenty on the server side. Keen to see exactly how that all works in TS, but I don't see this as urgent. I added the issue as a placeholder for this task.

If you are keen (generally you are, @pamtbaau!), I prefer to merge the `hughbris/issue11-git-library` branch into `develop` first. I think most of my checking is done so shouldn't take me long :)

**Comment by pamtbaau** [comment]
I haven't started refactoring TS yet... :-)  I'll wait until develop is leading.

May I presume you've tested my PR about handling renamed files?

**Comment by hughbris** [comment]
> I haven't started refactoring TS yet... :-) I'll wait until develop is leading.
> 

:P

> May I presume you've tested my PR about handling renamed files?

Yup, thought you would have got a notification: #28.

**Comment by hughbris** [comment]
Ref PR #30
