### ISSUE TITLE
JavaScript or Typescript

### ISSUE THREAD

**Issue by pamtbaau** [hughbris/grav-plugin-pushy#3]
If I would like to contribute to the repo, which language would you like to code to be in?

My personal preference is Typescript. If you prefer JavaScript, I'll have to share only the transpiled code.

Do you by the way have a bit more context about your plans? Eg. 
- How would you like the UI inside Admin to look like?
- What functionality are you thinking of to provide in Admin. 
  - Only a list of changed pages which can selectively be committed? 
  - Rollback? 
  - List of history? Undo a certain change?
  - How to handle merge conflicts when multiple users make changes to same page, commit and push?
  - ...

**Comment by hughbris** [comment]
Great! Firstly my plan was to at least start without any client scripting, but I think this will limit what I can do in terms of git (there's a note on that in the README todo section). I need to get this working for clients really quickly, so a simple form submission all-in-one commit is most immediately attractive. I may change my mind when I start building this in a few hours. Eventually I am pretty sure this will use AJAX.

I know the right answer is Typescript. I just don't know it yet or the transpiling stack. I really dislike npm if that's a necessary part of it. Not knowing Typescript has been inconvenient when trying to fix some other broken stuff in Grav like Form's file uploader, so maybe it's time.

My next tasks should provide you with a better idea for both parts of your question:

- [x] add a lot more detail into the README about configuration and installation
- [x] make the commit/publish button work (PHP/git already works, just need to trigger it)
