### ISSUE TITLE
Added front-end/backend async taskloop

### ISSUE THREAD

**Issue by pamtbaau** [hughbris/grav-plugin-pushy#4]
I've taken the liberty to add a few things:
- Created a UI to show dirty pages and allow user to check pages and commit/revert.
The UI resembles as much as possible the UI of Grav Admin.
- Commit/revert/other request are sent async to server and passed to RequestHandler
- RequestHandler detects the requested task (eg. fetch dirty pages/commit/revert/other) and handles the request. 
Except for the fetching of dirty pages, the task handlers are dummies.

Environment:
- Typescript
- SCSS
- Node

If you are interested, you may want to have a look at branch "pushy-admin-request". In case you don't like it,.. well I've had some fun anyway.

By the way, did you have a look at https://github.com/symplify/git-wrapper? The one you currently use is abandoned and quite old... Also, this one looks quite clean and simple.

![Untitled](https://user-images.githubusercontent.com/5120011/167908639-932d12df-bdb8-40e0-97fa-85a8cc20d22a.png)

**Comment by hughbris** [comment]
Thank you! Looks good, gonna take a look shortly.

> did you have a look at https://github.com/symplify/git-wrapper?

In the [comment which brought this plugin about on GitSync](https://github.com/trilbymedia/grav-plugin-git-sync/issues/213#issuecomment-1058575703), I mention that I discovered a few alternatives which look better and are active. Can't remember if that was one. Yes, I want to switch to one that's active and properly documented. Thanks for that too!

**Comment by hughbris** [comment]
Was added circa e2a27c961349f9325ace9fb8def3c6779e97e1fa.

BTW @pamtbaau, do you know about referencing and [closing issues in commit messages](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)?

**Comment by pamtbaau** [comment]
> BTW @pamtbaau, do you know about referencing and [closing issues in commit messages](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)?

No, I didn't... Interesting feature though. Will keep in mind.
