### ISSUE TITLE
Add a status "badge" to Admin menu

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-pushy#9]
Might be called a pill or something else:

![image](https://user-images.githubusercontent.com/288202/168939709-2f1c6e7a-b4fb-461f-8043-2bc994171140.png)

Showing how many changed/new items.

**Comment by pamtbaau** [comment]
These badges can be added when adding Pushy to the Admin menu. See for example in [Grav Admin itself](https://github.com/getgrav/grav-plugin-admin/blob/c03da191293e1b5ed9a8315ea4be4ebf14e5e484/admin.php#L857-L865):

```
// Pages
$count = new Container(['count' => function () { return $this->admin->pagesCount(); }]);
$twig->plugins_hooked_nav['PLUGIN_ADMIN.PAGES'] = [
      'route' => 'pages',
      'icon' => 'fa-file-text-o',
      'authorize' => ['admin.pages', 'admin.super'],
      'badge' => $count,
      'priority' => 5
];
```

`$twig->plugins_hooked_nav` is being called when Pushy add itself to the Admin menu. When Admin is started, the number of "dirty" pages can be added.

However, Pushy uses async calls to commit pages, hence the badge can no longer be update on the server.  Some JS should do the trick. That's doable, but unfortunately, the menu-item, nor the badge have proper id of classes.

**Comment by hughbris** [comment]
Sorry I had seen that option and this wasn't a call for help, just very quickly capturing my idea without wanting to look up the "how" again. Badge is indeed the term I was fishing for, thanks!

Thank you for being helpful and on the ball though.

> unfortunately, the menu-item, nor the badge have proper id of classes

(*or classes, I assume)

Try a PR in Admin to add easily selectable id/class attributes if you feel like it. I've had mixed luck with similar PRs though.

**Comment by hughbris** [comment]
Perhaps too late because you have solved this ..

> unfortunately, the menu-item, nor the badge have proper id of classes.

I noticed [this `class` menu property](https://github.com/hughbris/grav-plugin-pushy/blob/2c7790848f68e4dd8b908f680c7529cd1d6baec2/pushy.php#L122) that I left commented out in my Admin menu code that I copied (from Gitsync I think). I assume it adds a class and that the data property adds data attributes.

**Comment by hughbris** [comment]
Very satisfactory implementation provided in 23c4188804609b110e3e8d4eaf89b80a822de6cf.

Going to leave this open (sorry) because I would love to have an indicator of new items here as well. Should probably wait for #11 though.

**Comment by pamtbaau** [comment]
> I noticed [this class menu property](https://github.com/hughbris/grav-plugin-pushy/blob/2c7790848f68e4dd8b908f680c7529cd1d6baec2/pushy.php#L122) that I left commented out in my Admin menu code that I copied (from Gitsync I think). I assume it adds a class and that the data property adds data attributes.

Looking at the [nav.html.twig ](https://github.com/getgrav/grav-plugin-admin/blob/c03da191293e1b5ed9a8315ea4be4ebf14e5e484/themes/grav/templates/partials/nav.html.twig#L17-L44)template from Admin which generates the Admin menu, properties like `class` and `data` are not being referenced/used.

**Comment by hughbris** [comment]
Integrated circa 23c4188
